# Site settings
title: CRIS-MAS Project.
motto: Data analysis for making money in the end.
email: jumpers.jaeheung@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  growthhacking, marketing automation
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://HighLvRiver.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username: HighLvRiver

# Build settings
markdown: kramdown
